title: DHIL Documentation
description: Documentation for the Digital Humanities Innovation Lab at Simon Fraser University
theme: just-the-docs
url: https://docs.dhil.lib.sfu.ca
search_enabled: false
nav_enabled: false
heading_anchors: true
nav_external_links: []
gh_edit_link: false
color_scheme: dark
exclude:
  - docker-compose.yaml
  - Dockerfile
  - README.md
sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607